name: GitHub Actions Demo

on:
  push:
    branches:
    - "*"
    paths-ignore: 
    - ".github/**"
  pull_request:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "TriggeredBy"
      run: echo "${{ github.event_name }}"
    - uses: actions/checkout@v4
    - name: "Branch"
      run: echo "${{ github.ref }}"
    - name: "List all files of the repo"
      run: tree

  test:
    runs-on: ubuntu-latest
    needs: build
    environment: Test
    if: "${{ github.event_name }} == 'worflow_dispatch'"
    steps:
    - name: "Testing"
      run: echo "Testing..."

  load-test:
    runs-on: ubuntu-latest
    needs: build
    environment: Load-Test
    if: "${{ github.event_name }} == 'worflow_dispatch'"
    steps:
    - name: "Testing"
      run: echo "Testing..."
    - name: "Sleep"
      run: sleep 15

  production:
    runs-on: ubuntu-latest
    needs: [test, load-test]
    environment:
      name: Production
      url: https://writeabout.net
    if: "${{ github.event.inputs.environment }} == 'Production'"
    steps:
    - name: "Step 1 deploying"
      run: echo "Step 1 deploying..." && sleep 10
    - name: "Step 2 deploying"
      run: echo "Step 2 deploying..." && sleep 10
    - name: "Step 3 deploying"
      run: echo "Step 3 deploying..." && sleep 10
    - name: "Step 4 deploying"
      run: echo "Step 4 deploying..." && sleep 10
    - name: "Step 5 deploying"
      run: echo "Step 5 deploying..." && sleep 10
