name: GitHub Actions Demo

on:
  push:
    branches:
    - "*"
    paths-ignore: 
    - ".github/**"
  pull_request:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu
    steps:
    - name: "TriggeredBy"
      run: echo "${{ github.event_name }}"
    - name: "Branch"
      run: echo "${{ github.branch }}"
    - name: "List all files of the repo"
      run: tree
